### ISSUE TITLE
Adding numba to pip-requirements.txt

### ISSUE THREAD

**Issue by mcgibbon** [VulcanClimateModeling/fv3net#1118] opened 2021-03-31 21:54 UTC
It would be good to add numba to pip-requirements, since it sometimes gets installed locally either directly or as a dependency of manually-installed tools. This would lock the version which is good because it is an optional dependency of some of our dependencies.

When running `make lock_deps` with numba added to pip-requirements, however, several dependencies disappear from `constraints.txt`, most notably `scikit-learn`. It is not clear why this happens, and it should be fixed before re-building the constraints file.

**Comment by oliverwm1** [comment] 2021-04-13 16:08
I just tried running `make lock_pip` and also had `scikit-learn` disappear from the `constraints.txt`. I think the issue is that `scikit-learn` is no longer listed in the prognostic run requirements, and the `make lock_pip` rule does not use the `fv3fit` requirements.txt (which does list `scikit-learn`).

I also get various other changes to the `constraints.txt` file, which I guess are system or pip version dependent? Not sure. But perhaps we should have a test in which CI generates the `constraints.txt` in a well defined environment and makes sure it's the same as what's checked in to fv3net?

**Comment by mcgibbon** [comment] 2021-04-13 18:06
> But perhaps we should have a test in which CI generates the constraints.txt in a well defined environment and makes sure it's the same as what's checked in to fv3net?

This could be a good idea, since the command should only change when the requirements files are updated.

**Comment by nbren12** [comment] 2021-04-13 18:18
> But perhaps we should have a test in which CI generates the constraints.txt in a well defined environment and makes sure it's the same as what's checked in to fv3net?

The CI should be deterministic. If we have it generate the `constraints.txt` it will not be. This is why tools like poetry, and the fv3net monorepo have different places for specifying abstract dependencies (e.g. setup.py) and concrete ones (poetry.lock).

**Comment by nbren12** [comment] 2021-04-13 18:22
>  also get various other changes to the constraints.txt file, which I guess are system or pip version dependent?
These depend on the state of pypi and the python version, etc. Generating a lock file is deterministic. Installing from one is.

**Comment by mcgibbon** [comment] 2021-04-13 19:17
Let's not do a test of constraints.txt then.

We came up with two action items on Slack:
- Add two checkboxes to the "requirements changes" section of the PR template, one that says the `make lock_deps` or `make lock_pip` have been run as appropriate if the requirements are updated, and another saying that if there are requirements changes, those are the only changes in the PR.
- Communicate these more careful review procedures to the team

**Closed** 2021-04-13 20:59 UTC
